# Generated by Django 5.1.7 on 2025-03-12 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nama', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nasabah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nama', models.CharField(max_length=255)),
                ('poin', models.IntegerField(default=0)),
                ('no_rekening', models.CharField(max_length=20, unique=True)),
                ('jenis_kelamin', models.CharField(max_length=10)),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PenukaranPoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('poin', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('nasabah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.nasabah')),
            ],
        ),
        migrations.CreateModel(
            name='Setoran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('berat', models.FloatField()),
                ('poin', models.IntegerField()),
                ('nasabah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.nasabah')),
            ],
        ),
    ]
