# Generated by Django 5.1.7 on 2025-03-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('nasabah', 'Nasabah'), ('admin', 'Admin')], max_length=15),
        ),
    ]
