# Generated by Django 5.1.7 on 2025-03-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('nasabah', 'Nasabah'), ('admin', 'Admin')], default='nasabah', max_length=10),
        ),
    ]
