# Generated by Django 5.1.7 on 2025-03-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_penukaranpoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reserved_poin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='penukaranpoin',
            name='jumlah_poin',
            field=models.PositiveIntegerField(),
        ),
    ]
