# Generated by Django 5.1.7 on 2025-04-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_penukaranpoin_jumlah_poin_pointaddition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointaddition',
            name='points',
            field=models.IntegerField(editable=False),
        ),
    ]
